### ISSUE TITLE
Incompatibility with OpenCV 4.0+

### ISSUE THREAD

**Issue by yfaqh** [BingyaoHuang/DeProCams#2]
> After I prepared the source code and dataset(I changed the GPU id in train_DeProCams.py),  I got an exception below when I run train_DeProCams.py. 

Traceback (most recent call last):
  File "train_DeProCams.py", line 134, in <module>
    cam_surf, cam_train, cam_valid, prj_train, prj_valid, mask, mask_corners, calib_data = loadData(dataset_root, data_name, cam_size)
  File "/media/wit/Data21/Research/yh/paper_code/AR/DeProCams-main/src/python/trainNetwork.py", line 69, in loadData
    im_mask, _, mask_corners = ImgProc.threshDeProCams(im_diff[..., 0])  # use thresholded surface image as mask
  File "/media/wit/Data21/Research/yh/paper_code/AR/DeProCams-main/src/python/ImgProc.py", line 42, in threshDeProCams
    im_contours, contours, hierarchy = cv.findContours(np.uint8(im_mask), cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

> I print the three parameters of findContours, the first param np.uint8(im_mask) is 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

> It is wired, is there anything wrong? @BingyaoHuang

**Comment by BingyaoHuang** [comment]
@yfaqh Maybe it's the wrong OpenCV version.

As suggested in [requirements.txt](../blob/main/requirements.txt), DeProCams uses OpenCV 3.4.4. I guess you're using a higher version, and the behavior of `cv.findContours` has been changed since OpenCV 4.0. 

Also, please follow [requirements.txt](../blob/main/requirements.txt) to avoid other potential incompatibility issues.

**Comment by yfaqh** [comment]
@BingyaoHuang 
Thanks for replying. It works. 👍
The previous version of my OpenCV is 4.5.1 and I changed it to 3.4.4.
Great code! I have successfully reproduced the training of DeProCams. 😁

**Comment by BingyaoHuang** [comment]
Great! Feel free to open a new issue if you have any other questions.
